language: node_js
node_js:
  - "6.11"
sudo: required
services:
  - mongodb
  - redis-server
  - docker
cache:
  directories:
  - node_modules
git:
  depth: 3
stages:
  - test
  - name: deploy
    if: branch = ci-build

jobs:
  include:
    - stage: test
      script: echo 'testing stage'
    - stage: deploy
      script: echo 'deploy stage'
#script:
  # - yarn test:check-coverage
  #- npm run test
#  - ./devops/build-api.sh
