language: node_js
node_js:
  - "6.11"
sudo: required
services:
  - mongodb
  - redis-server
  - docker
cache:
  directories:
  - node_modules
git:
  depth: 3

jobs:
  include:
    - script:
      - npm run test
    - if: branch = ci-build
      script: 
        - ./devops/build-api.sh
        - cd devops; ./build-mongodb.sh
