language: node_js
node_js:
  - "6.11"
sudo: required
services:
  - mongodb
  - redis-server
  - docker
cache:
  directories:
  - node_modules
git:
  depth: 3

jobs:
  include:
    - if: branch = develop
      script: echo 'this is develop branch'
    - if: branch = ci-build
      script: echo 'this is ci-build branch'
#script:
  # - yarn test:check-coverage
  #- npm run test
#  - ./devops/build-api.sh
